### ISSUE TITLE
Add Reddit

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/awesome-open-company#1]
Lacking an [explicit openness/transparency page](../wiki/Inclusion-guidelines), even though it's tacitly known that they value those principles. The [about page](http://www.reddit.com/about/) doesn't mention anything; there's a [blog post](http://www.redditblog.com/2008/06/reddit-goes-open-source.html) but it's not something permanent and easily findable (e.g. from the site's navigation menu).

Pinging @reddit (hope this works) for feedback.

**Comment by waldyrious** [comment]
Looks like at-mentioning organizations doesn't notify the members. I won't individually ping [all 14 members](https://github.com/orgs/reddit/people), so I'll mention the top 3 contributors: @bsimpson64, @spladug, @kemitche. Let me know what you guys think :)

**Comment by spladug** [comment]
How's this? https://www.reddit.com/about/values :)

**Comment by waldyrious** [comment]
It's certainly a little less orthodox compared to most of the other similar pages included in this list, but I suppose

> "Default to transparency, and when you can’t be transparent, be honest."

and

> "Be stewards, not dictators. The community owns itself."

Are the ones closest to the spirit of this initiative. It might take a careful reading to find them, but since they are there, it fits the parameters. The blog post is a good companion to the page. Thanks for doing this! I'll add it to the list.

**Comment by waldyrious** [comment]
Although the recent controversy is mostly over, I don't feel comfortable re-adding the company based on such vague commitments to openness (which have proven insufficient by the very fact that the issues mentioned in #15 did happen). If a more decisive statement (i.e. an explicit commitment) regarding openness and transparency is adopted, I'll add it, but since there are no signs of that so far, I'll close the issue for now.
