### ISSUE TITLE
Add Dangerous Prototypes

### ISSUE THREAD

**Issue by kasbah** [waldyrious/awesome-open-company#11]
[Dangerous Prototypes](http://dangerousprototypes.com/) started as making a new open source hardware (OSHW) project every month, while that may have been a bit ambitious they do have several popular OSHW electronics projects with accompanying open source software.

**Comment by waldyrious** [comment]
Nice one! The openness spirit is strong with these ones :) It's a little unclear whether they're actually a commercial entity, but the [about page](http://dangerousprototypes.com/docs/About) (which contains lots of nice content about open business, btw) does clarify that they do have 8 paid contributors. So for me, that's a definite yes. Please open a PR to get the contribution credited to you. :)

**Comment by waldyrious** [comment]
fixed in 2bd8926
