### ISSUE TITLE
Add Arduino LLC

### ISSUE THREAD

**Issue by kasbah** [waldyrious/awesome-open-company#8]
Arduino LLC need no introduction, all [their products](http://www.arduino.cc/en/Main/Products) are open source and so is the [supporting software](https://github.com/arduino/arduino).

**Comment by waldyrious** [comment]
Thanks for the suggestions! If you don't mind, can you open separate issues for each company? I'll comment below about Arduino, and will add comments about the others in the corresponding issues.

Arduino of course requires no introduction (in the openness front) for those who already know a little about it, but it would be nice if the openness policy was more explicit. I think we can link to [Introduction](http://www.arduino.cc/en/Guide/Introduction) page, whose "Why Arduino?" section describes the open hardware and open software aspects of the project. Do you know of any better page that could be used?

**Comment by kasbah** [comment]
I don't I am afraid. There is a short section in the [FAQ](http://www.arduino.cc/en/Main/FAQ) as well.

**Comment by waldyrious** [comment]
Yeah, I noticed that in the FAQ but since it's a larger document, I suppose the Introduction page works better for our purposes. Feel free to open a pull request :)
